python -m t5.models.mesh_transformer_main \
--module_import="tasks.all_all" \
--model_dir="models/base/" \
--gin_param="utils.run.mesh_shape = 'model:1,batch:1'" \
--gin_param="utils.run.mesh_devices = ['gpu:0']" \
--gin_param="MIXTURE_NAME = 'korsmr'" \
--gin_param="utils.run.train_steps=756700" \
--gin_file="dataset.gin" \
--gin_param="SentencePieceVocabulary.extra_ids=100" \
--gin_file="models/base/operative_config.gin" \
--gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
--gin_param="utils.run.batch_size=('tokens_per_batch', 2560)" \
--gin_param="serialize_num_microbatches.tokens_per_microbatch_per_replica = 512" \
--gin_param="utils.run.save_checkpoints_steps=100"